<?php

/**
 * @file
 * Entity Reference Autocomplete (Test).
 */

/**
 * {@inheritdoc}
 *
 * @internal
 * @see \Drupal\entityreference_autocomplete\Tests\BaseTest::buildForm()
 */
function entityreference_autocomplete_test_form(array $form, array &$form_state, $entity_type, $default_value, $cardinality = 1, array $bundles = array(), array $query_settings = array()) {
  if (empty($query_settings)) {
    $query_settings = array(
      'limit' => 50,
    );
  }

  $form['entityreference'] = array(
    '#type' => 'entityreference',
    '#default_value' => $default_value,
    '#era_bundles' => $bundles,
    '#era_cardinality' => $cardinality,
    '#era_entity_type' => $entity_type,
    '#era_query_settings' => $query_settings,
  );

  return $form;
}
